[boards]
boards_dir=boards

[env:esp32s3]
platform = espressif32
framework = espidf
board = esp32-s3-devkitc-1
monitor_speed = 115200
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.partitions = max_app_4MB.csv
board_upload.flash_size = 4MB
lib_deps =
  codewitch-honey-crisis/htcw_uix
  codewitch-honey-crisis/htcw_json
  codewitch-honey-crisis/htcw_esp_wifi_manager
build_unflags = -std=gnu++11
